# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20160423_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='grupo_publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.Grupo'),
        ),
    ]
