# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_publicacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='uploadfoto',
            field=models.ImageField(blank=True, upload_to='/media/'),
        ),
    ]
