# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-25 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20160424_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='uploadfoto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
