# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-25 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20160424_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='uploadfoto',
        ),
    ]
